### ISSUE TITLE
Error: Cannot find module 'bcrypt'

### ISSUE THREAD

**Issue by jeekajoo** [cozy/cozy-proxy#180] opened 2015-09-26 17:25 UTC
Hi,
Since last update, it looks like proxy is broken due a missing dependency.
I tried to uninstall / reinstall it without success.
```bash
# cozy-monitor uninstall proxy
info - Uninstall started for proxy...
info - proxy successfully uninstalled.
# cozy-monitor install proxy
info - Install started for proxy...
info - proxy was successfully installed.
# cozy-monitor start proxy
info - Starting proxy...
error - An error occured:
error - Start failed for proxy.
```

/usr/local/var/log/cozy/proxy.log-backup:
```python
Cannot find module 'bcrypt'
Error: Cannot find module 'bcrypt'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/cozy/apps/proxy/build/server/lib/passport_configurator.js:4:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
```bash
# cozy-monitor status
mta: down
couch: up
controller: up
data-system: up
home: up
proxy: down
index: up
kresus: up
databrowser: up
konnectors: up
files: up
```
```bash
# npm -g ls -depth 0
/usr/local/lib
├── cozy-controller@2.0.31
└── cozy-monitor@1.2.29
```
Thanks
J.

**Comment by clochix** [comment] 2015-09-26 18:18
Hi @jeekajoo,

could you go to `/usr/local/cozy/apps/proxy`, run `npm install` and give us the output. Seems like there's a problem installing `bcrypt` module.
Also, could you check your Node version ? Some Debian users recently got an update to Node 0.4, and Cozy is not compatible for now with this version.

**Comment by jeekajoo** [comment] 2015-09-26 18:33
Here it is:
```
/usr/local/cozy/apps/proxy# npm install
npm WARN package.json cozy-proxy@2.1.3 No repository field.
 
> bcrypt@0.8.5 install /usr/local/cozy/apps/proxy/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory '/usr/local/cozy/apps/proxy/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from ../src/bcrypt_node.cc:1:0:
../node_modules/nan/nan.h:318:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
bcrypt_lib.target.mk:86: recipe for target 'Release/obj.target/bcrypt_lib/src/bcrypt_node.o' failed
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory '/usr/local/cozy/apps/proxy/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/cozy/apps/proxy/node_modules/bcrypt
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.5 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /usr/local/cozy/apps/proxy
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
-
> ws@0.4.32 install /usr/local/cozy/apps/proxy/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/usr/local/cozy/apps/proxy/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory '/usr/local/cozy/apps/proxy/node_modules/socket.io-client/node_modules/ws/build'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/cozy/apps/proxy/npm-debug.log
npm ERR! not ok code 0
```

```
# node -v
v0.10.29
# npm -v
1.4.21
# cat /etc/issue
Debian GNU/Linux 8 \n \l
# dpkg -l | grep cozy
ii  cozy                              1.13                         all          <insert up to 60 chars description>
ii  cozy-indexer                      1.0.6                        all          <insert up to 60 chars description>
```
Thanks

**Comment by clochix** [comment] 2015-09-26 19:09
Maybe related to https://github.com/ncb000gt/node.bcrypt.js/issues/326 and https://github.com/nodejs/nan/issues/414
Could you try to update node-gyp ?

**Comment by clochix** [comment] 2015-09-27 08:24
Maybe related to https://github.com/ncb000gt/node.bcrypt.js/issues/326 and https://github.com/nodejs/nan/issues/414
Could you try to update node-gyp ?

(sorry, I answered yesterday but forgot to publish by comment :'( )

**Comment by jeekajoo** [comment] 2015-09-27 18:19
`node-gyp` was installed from debian (jessie) packages as it is a dependency https://github.com/cozy/cozy-debian/blob/master/debian/control#L17 of your official debian package.

**Comment by clochix** [comment] 2015-09-27 19:34
Yes I know node-gyp comes with npm. Did you had a look at the tickets I mentioned in my previous comment ? They seems related. Unfortunately, I'm unable to reproduce your problem for now :-S

**Comment by jeekajoo** [comment] 2015-09-27 19:54
as suggested in https://github.com/nodejs/nan/issues/414#issuecomment-131756213, I did `npm -g install npm` to upgrade the debian's npm to npm's npm and that presumably included node-gyp and that fixed it.

now using `node-gyp@3.0.3`

```
#  npm -g ls
/usr/local/lib
├─┬ cozy-controller@2.0.31
│ ├─┬ americano@0.3.10
│ │ ├─┬ body-parser@1.3.0
│ │ │ ├── bytes@1.0.0
│ │ │ ├── qs@0.6.6
│ │ │ ├── raw-body@1.1.6
│ │ │ └─┬ type-is@1.2.0
│ │ │   └── mime@1.2.11
│ │ ├── commander@2.2.0
│ │ ├── errorhandler@1.0.1
│ │ ├─┬ express@4.4.0
│ │ │ ├─┬ accepts@1.0.2
│ │ │ │ ├── mime@1.2.11
│ │ │ │ └── negotiator@0.4.5
│ │ │ ├── buffer-crc32@0.2.1
│ │ │ ├── cookie@0.1.2
│ │ │ ├── cookie-signature@1.0.3
│ │ │ ├── debug@0.8.1
│ │ │ ├── escape-html@1.0.1
│ │ │ ├── fresh@0.2.2
│ │ │ ├── merge-descriptors@0.0.2
│ │ │ ├── methods@1.0.0
│ │ │ ├── parseurl@1.0.1
│ │ │ ├── path-to-regexp@0.1.2
│ │ │ ├─┬ proxy-addr@1.0.0
│ │ │ │ └── ipaddr.js@0.1.2
│ │ │ ├── qs@0.6.6
│ │ │ ├── range-parser@1.0.0
│ │ │ ├─┬ send@0.4.0
│ │ │ │ ├── finished@1.1.4
│ │ │ │ └── mime@1.2.11
│ │ │ ├── serve-static@1.2.0
│ │ │ ├─┬ type-is@1.2.0
│ │ │ │ └── mime@1.2.11
│ │ │ └── utils-merge@1.0.0
│ │ ├─┬ method-override@2.0.0
│ │ │ ├── methods@1.0.0
│ │ │ └── parseurl@1.0.1
│ │ ├─┬ morgan@1.1.1
│ │ │ └── bytes@1.0.0
│ │ └── printit@0.1.3
│ ├─┬ americano-cozy@0.2.8
│ │ ├─┬ jugglingdb@0.2.14
│ │ │ └── inflection@1.2.7
│ │ ├─┬ jugglingdb-cozy-adapter@0.4.12
│ │ │ └─┬ request-json@0.4.4
│ │ │   └─┬ request@2.21.0
│ │ │     ├── aws-sign@0.3.0
│ │ │     ├── cookie-jar@0.3.0
│ │ │     ├── forever-agent@0.5.2
│ │ │     ├─┬ form-data@0.0.8
│ │ │     │ ├── async@0.2.10
│ │ │     │ └─┬ combined-stream@0.0.7
│ │ │     │   └── delayed-stream@0.0.5
│ │ │     ├─┬ hawk@0.13.1
│ │ │     │ ├─┬ boom@0.4.2
│ │ │     │ │ └── hoek@0.9.1
│ │ │     │ ├── cryptiles@0.2.2
│ │ │     │ ├── hoek@0.8.5
│ │ │     │ └─┬ sntp@0.2.4
│ │ │     │   └── hoek@0.9.1
│ │ │     ├─┬ http-signature@0.9.11
│ │ │     │ ├── asn1@0.1.11
│ │ │     │ ├── assert-plus@0.1.2
│ │ │     │ └── ctype@0.5.2
│ │ │     ├── json-stringify-safe@4.0.0
│ │ │     ├── mime@1.2.11
│ │ │     ├── node-uuid@1.4.3
│ │ │     ├── oauth-sign@0.3.0
│ │ │     ├── qs@0.6.6
│ │ │     └── tunnel-agent@0.3.0
│ │ └── printit@0.1.3
│ ├── async@0.9.0
│ ├─┬ cozy-controller-carapace@0.8.0
│ │ ├── async@0.1.22
│ │ ├── eventemitter2@0.4.14
│ │ ├─┬ optimist@0.3.7
│ │ │ └── wordwrap@0.0.3
│ │ └── semver@1.0.14
│ ├─┬ forever-monitor@1.3.0
│ │ ├─┬ broadway@0.2.10
│ │ │ ├─┬ cliff@0.1.8
│ │ │ │ ├── colors@0.6.2
│ │ │ │ ├── eyes@0.1.8
│ │ │ │ └─┬ winston@0.6.2
│ │ │ │   ├── async@0.1.22
│ │ │ │   ├── cycle@1.0.3
│ │ │ │   ├── pkginfo@0.2.3
│ │ │ │   ├── request@2.9.203
│ │ │ │   └── stack-trace@0.0.9
│ │ │ ├── eventemitter2@0.4.14
│ │ │ ├─┬ nconf@0.6.9
│ │ │ │ ├── async@0.2.9
│ │ │ │ ├── ini@1.3.4
│ │ │ │ └─┬ optimist@0.6.0
│ │ │ │   ├── minimist@0.0.10
│ │ │ │   └── wordwrap@0.0.3
│ │ │ ├─┬ utile@0.2.1
│ │ │ │ ├── async@0.2.10
│ │ │ │ ├── deep-equal@1.0.1
│ │ │ │ ├── i@0.3.3
│ │ │ │ └── ncp@0.4.2
│ │ │ └─┬ winston@0.7.2
│ │ │   ├── async@0.2.10
│ │ │   ├── colors@0.6.2
│ │ │   ├── cycle@1.0.3
│ │ │   ├── eyes@0.1.8
│ │ │   ├─┬ request@2.16.6
│ │ │   │ ├── aws-sign@0.2.0
│ │ │   │ ├── cookie-jar@0.2.0
│ │ │   │ ├── forever-agent@0.2.0
│ │ │   │ ├─┬ form-data@0.0.10
│ │ │   │ │ └─┬ combined-stream@0.0.7
│ │ │   │ │   └── delayed-stream@0.0.5
│ │ │   │ ├─┬ hawk@0.10.2
│ │ │   │ │ ├── boom@0.3.8
│ │ │   │ │ ├── cryptiles@0.1.3
│ │ │   │ │ ├── hoek@0.7.6
│ │ │   │ │ └── sntp@0.1.4
│ │ │   │ ├── json-stringify-safe@3.0.0
│ │ │   │ ├── mime@1.2.11
│ │ │   │ ├── node-uuid@1.4.3
│ │ │   │ ├── oauth-sign@0.2.0
│ │ │   │ ├── qs@0.5.6
│ │ │   │ └── tunnel-agent@0.2.0
│ │ │   └── stack-trace@0.0.9
│ │ ├─┬ minimatch@0.2.14
│ │ │ ├── lru-cache@2.7.0
│ │ │ └── sigmund@1.0.1
│ │ ├── pkginfo@0.3.0
│ │ ├─┬ ps-tree@0.0.3
│ │ │ └─┬ event-stream@0.5.3
│ │ │   └─┬ optimist@0.2.8
│ │ │     └── wordwrap@0.0.3
│ │ ├─┬ utile@0.1.7
│ │ │ ├── async@0.1.22
│ │ │ ├── deep-equal@1.0.1
│ │ │ ├── i@0.3.3
│ │ │ ├── ncp@0.2.7
│ │ │ └── rimraf@1.0.9
│ │ └── watch@0.5.1
│ ├─┬ mkdirp@0.5.0
│ │ └── minimist@0.0.8
│ ├── mozilla-version-comparator@1.0.2
│ ├─┬ npm@1.4.28
│ │ ├── abbrev@1.0.5
│ │ ├── ansi@0.3.0
│ │ ├── ansicolors@0.3.2
│ │ ├── ansistyles@0.1.3
│ │ ├── archy@0.0.2
│ │ ├── block-stream@0.0.7
│ │ ├── char-spinner@1.0.1
│ │ ├── child-process-close@0.1.1
│ │ ├── chmodr@0.1.0
│ │ ├── chownr@0.0.1
│ │ ├── cmd-shim@2.0.0 (git://github.com/othiym23/cmd-shim#12de64ca97f45ac600910092f19afacc3d5376dd)
│ │ ├─┬ columnify@1.2.1
│ │ │ ├─┬ strip-ansi@1.0.0
│ │ │ │ └── ansi-regex@0.2.1
│ │ │ └─┬ wcwidth@1.0.0
│ │ │   └─┬ defaults@1.0.0
│ │ │     └── clone@0.1.18
│ │ ├── editor@0.1.0
│ │ ├── fstream@1.0.2
│ │ ├─┬ fstream-npm@1.0.0
│ │ │ └── fstream-ignore@1.0.1
│ │ ├── github-url-from-git@1.4.0
│ │ ├── github-url-from-username-repo@1.0.0
│ │ ├── glob@4.0.5
│ │ ├── graceful-fs@3.0.2
│ │ ├── inflight@1.0.1
│ │ ├── inherits@2.0.1
│ │ ├── ini@1.2.1
│ │ ├─┬ init-package-json@1.0.0
│ │ │ └── promzard@0.2.2
│ │ ├── lockfile@1.0.0
│ │ ├── lru-cache@2.5.0
│ │ ├─┬ minimatch@1.0.0
│ │ │ └── sigmund@1.0.0
│ │ ├─┬ mkdirp@0.5.0
│ │ │ └── minimist@0.0.8
│ │ ├── node-gyp@1.0.1
│ │ ├── nopt@3.0.1
│ │ ├── npm-cache-filename@1.0.1
│ │ ├── npm-install-checks@1.0.2
│ │ ├── npm-registry-client@2.0.7
│ │ ├── npm-user-validate@0.1.0
│ │ ├─┬ npmconf@1.1.8
│ │ │ └─┬ config-chain@1.1.8
│ │ │   └── proto-list@1.2.3
│ │ ├── npmlog@0.1.1
│ │ ├── once@1.3.0
│ │ ├── opener@1.3.0
│ │ ├── osenv@0.1.0
│ │ ├── path-is-inside@1.0.1
│ │ ├─┬ read@1.0.5
│ │ │ └── mute-stream@0.0.4
│ │ ├─┬ read-installed@2.0.5
│ │ │ └── util-extend@1.0.1
│ │ ├─┬ read-package-json@1.2.7
│ │ │ └── normalize-package-data@1.0.1
│ │ ├─┬ request@2.42.0
│ │ │ ├── aws-sign2@0.5.0
│ │ │ ├─┬ bl@0.9.1
│ │ │ │ └─┬ readable-stream@1.0.31
│ │ │ │   ├── core-util-is@1.0.1
│ │ │ │   ├── isarray@0.0.1
│ │ │ │   └── string_decoder@0.10.31
│ │ │ ├── caseless@0.6.0
│ │ │ ├── forever-agent@0.5.2
│ │ │ ├─┬ form-data@0.1.4
│ │ │ │ ├── async@0.9.0
│ │ │ │ ├─┬ combined-stream@0.0.5
│ │ │ │ │ └── delayed-stream@0.0.5
│ │ │ │ └── mime@1.2.11
│ │ │ ├─┬ hawk@1.1.1
│ │ │ │ ├── boom@0.4.2
│ │ │ │ ├── cryptiles@0.2.2
│ │ │ │ ├── hoek@0.9.1
│ │ │ │ └── sntp@0.2.4
│ │ │ ├─┬ http-signature@0.10.0
│ │ │ │ ├── asn1@0.1.11
│ │ │ │ ├── assert-plus@0.1.2
│ │ │ │ └── ctype@0.5.2
│ │ │ ├── json-stringify-safe@5.0.0
│ │ │ ├── mime-types@1.0.2
│ │ │ ├── node-uuid@1.4.1
│ │ │ ├── oauth-sign@0.4.0
│ │ │ ├── qs@1.2.2
│ │ │ ├── stringstream@0.0.4
│ │ │ ├─┬ tough-cookie@0.12.1
│ │ │ │ └── punycode@1.3.1
│ │ │ └── tunnel-agent@0.4.0
│ │ ├── retry@0.6.0
│ │ ├── rimraf@2.2.8
│ │ ├── semver@2.3.0
│ │ ├─┬ sha@1.2.4
│ │ │ └─┬ readable-stream@1.0.27-1
│ │ │   ├── core-util-is@1.0.1
│ │ │   ├── isarray@0.0.1
│ │ │   └── string_decoder@0.10.25-1
│ │ ├── slide@1.1.6
│ │ ├── sorted-object@1.0.0
│ │ ├── tar@1.0.1
│ │ ├── text-table@0.2.0
│ │ ├── uid-number@0.0.5
│ │ └── which@1.0.5
│ ├── printit@0.1.6
│ ├─┬ request@2.53.0
│ │ ├── aws-sign2@0.5.0
│ │ ├─┬ bl@0.9.4
│ │ │ └─┬ readable-stream@1.0.33
│ │ │   ├── core-util-is@1.0.1
│ │ │   ├── inherits@2.0.1
│ │ │   ├── isarray@0.0.1
│ │ │   └── string_decoder@0.10.31
│ │ ├── caseless@0.9.0
│ │ ├─┬ combined-stream@0.0.7
│ │ │ └── delayed-stream@0.0.5
│ │ ├── forever-agent@0.5.2
│ │ ├── form-data@0.2.0
│ │ ├─┬ hawk@2.3.1
│ │ │ ├── boom@2.8.0
│ │ │ ├── cryptiles@2.0.5
│ │ │ ├── hoek@2.16.0
│ │ │ └── sntp@1.0.9
│ │ ├─┬ http-signature@0.10.1
│ │ │ ├── asn1@0.1.11
│ │ │ ├── assert-plus@0.1.5
│ │ │ └── ctype@0.5.3
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.1
│ │ ├─┬ mime-types@2.0.14
│ │ │ └── mime-db@1.12.0
│ │ ├── node-uuid@1.4.3
│ │ ├── oauth-sign@0.6.0
│ │ ├── qs@2.3.3
│ │ ├── stringstream@0.0.4
│ │ ├── tough-cookie@2.0.0
│ │ └── tunnel-agent@0.4.1
│ ├─┬ request-json-light@0.5.15
│ │ ├─┬ form-data@0.1.4
│ │ │ ├─┬ combined-stream@0.0.7
│ │ │ │ └── delayed-stream@0.0.5
│ │ │ └── mime@1.2.11
│ │ └── mime@1.3.4
│ ├── rimraf@2.2.8
│ └─┬ tar@0.1.17
│   ├─┬ block-stream@0.0.8
│   │ └── inherits@2.0.1
│   ├─┬ fstream@0.1.31
│   │ ├── graceful-fs@3.0.8
│   │ └── inherits@2.0.1
│   └── inherits@1.0.2
├─┬ cozy-monitor@1.2.29
│ ├─┬ always-tail@0.1.1
│ │ └── debug@0.7.4
│ ├── async@0.9.0
│ ├─┬ axon@0.6.1
│ │ ├── configurable@0.0.1
│ │ ├─┬ debug@2.2.0
│ │ │ └── ms@0.7.1
│ │ └── escape-regexp@0.0.1
│ ├── coffee-script@1.9.0
│ ├── colors@1.1.2
│ ├─┬ commander@1.0.5
│ │ └── keypress@0.1.0
│ ├─┬ cozy-clients@1.0.3
│ │ └─┬ request-json@0.4.10
│ │   └─┬ request@2.34.0
│ │     ├── aws-sign2@0.5.0
│ │     ├── forever-agent@0.5.2
│ │     ├─┬ form-data@0.1.4
│ │     │ └─┬ combined-stream@0.0.7
│ │     │   └── delayed-stream@0.0.5
│ │     ├─┬ hawk@1.0.0
│ │     │ ├── boom@0.4.2
│ │     │ ├── cryptiles@0.2.2
│ │     │ ├── hoek@0.9.1
│ │     │ └── sntp@0.2.4
│ │     ├─┬ http-signature@0.10.1
│ │     │ ├── asn1@0.1.11
│ │     │ ├── assert-plus@0.1.5
│ │     │ └── ctype@0.5.3
│ │     ├── json-stringify-safe@5.0.1
│ │     ├── mime@1.2.11
│ │     ├── node-uuid@1.4.3
│ │     ├── oauth-sign@0.3.0
│ │     ├── qs@0.6.6
│ │     ├── tough-cookie@2.0.0
│ │     └── tunnel-agent@0.3.0
│ ├── printit@0.1.3
│ ├─┬ request-json-light@0.5.10
│ │ ├─┬ form-data@0.1.4
│ │ │ ├─┬ combined-stream@0.0.7
│ │ │ │ └── delayed-stream@0.0.5
│ │ │ └── mime@1.2.11
│ │ └── mime@1.3.4
│ └── shelljs@0.3.0
└─┬ npm@3.3.4
  ├── abbrev@1.0.7
  ├── ansi@0.3.0
  ├── ansi-regex@2.0.0
  ├── ansi-styles@2.1.0
  ├── ansicolors@0.3.2
  ├── ansistyles@0.1.3
  ├── aproba@1.0.1
  ├── archy@1.0.0
  ├── are-we-there-yet@1.0.4
  ├── array-index@0.1.1
  ├── asap@2.0.3
  ├── asn1@0.1.11
  ├── assert-plus@0.1.5
  ├── async@1.4.2
  ├── async-some@1.0.2
  ├── aws-sign2@0.5.0
  ├── balanced-match@0.2.0
  ├─┬ bl@1.0.0
  │ └── readable-stream@2.0.2
  ├── block-stream@0.0.8
  ├── bluebird@2.10.0
  ├── boom@2.8.0
  ├── brace-expansion@1.1.0
  ├── builtin-modules@1.1.0
  ├── builtins@0.0.7
  ├── caseless@0.11.0
  ├── chalk@1.1.1
  ├── chownr@1.0.1
  ├── clone@0.1.19
  ├─┬ cmd-shim@2.0.1
  │ └── graceful-fs@3.0.8
  ├── columnify@1.5.2
  ├── combined-stream@1.0.5
  ├── commander@2.8.1
  ├── concat-map@0.0.1
  ├─┬ concat-stream@1.5.0
  │ └── readable-stream@2.0.2
  ├── config-chain@1.1.9
  ├── core-util-is@1.0.1
  ├── cryptiles@2.0.5
  ├── ctype@0.5.3
  ├── debug@2.2.0
  ├── debuglog@1.0.1
  ├── defaults@1.0.2
  ├── delayed-stream@1.0.0
  ├── delegates@0.1.0
  ├── dezalgo@1.0.3
  ├── editor@1.0.0
  ├── escape-string-regexp@1.0.3
  ├── extend@3.0.0
  ├── forever-agent@0.6.1
  ├── form-data@1.0.0-rc3
  ├── fs-vacuum@1.2.7
  ├── fs-write-stream-atomic@1.0.4
  ├── fstream@1.0.8
  ├── fstream-ignore@1.0.2
  ├── fstream-npm@1.0.5
  ├── gauge@1.2.2
  ├── generate-function@2.0.0
  ├── generate-object-property@1.2.0
  ├── glob@5.0.14
  ├── graceful-fs@4.1.2
  ├── graceful-readlink@1.0.1
  ├── har-validator@1.8.0
  ├── has-ansi@2.0.0
  ├── has-unicode@1.0.0
  ├── hawk@3.1.0
  ├── hoek@2.16.2
  ├── hosted-git-info@2.1.4
  ├── http-signature@0.11.0
  ├── iferr@0.1.5
  ├── inflight@1.0.4
  ├── inherits@2.0.1
  ├── ini@1.3.4
  ├── init-package-json@1.9.1
  ├── is-absolute@0.1.7
  ├── is-builtin-module@1.0.0
  ├── is-my-json-valid@2.12.2
  ├── is-property@1.0.2
  ├── is-relative@0.1.3
  ├── isarray@0.0.1
  ├── isstream@0.1.2
  ├── jju@1.2.1
  ├── json-parse-helpfulerror@1.0.3
  ├── json-stringify-safe@5.0.1
  ├── jsonpointer@2.0.0
  ├── lockfile@1.0.1
  ├── lodash._arraycopy@3.0.0
  ├── lodash._arrayeach@3.0.0
  ├── lodash._baseassign@3.2.0
  ├── lodash._basecallback@3.3.1
  ├── lodash._baseclone@3.3.0
  ├── lodash._basecopy@3.0.1
  ├── lodash._basedifference@3.0.3
  ├── lodash._baseflatten@3.1.4
  ├── lodash._basefor@3.0.2
  ├── lodash._baseindexof@3.1.0
  ├── lodash._baseisequal@3.0.7
  ├── lodash._basetostring@3.0.1
  ├── lodash._baseuniq@3.0.3
  ├── lodash._bindcallback@3.0.1
  ├── lodash._cacheindexof@3.0.2
  ├── lodash._createcache@3.1.2
  ├── lodash._createpadding@3.6.1
  ├── lodash._getnative@3.9.1
  ├── lodash._isiterateecall@3.0.9
  ├── lodash.clonedeep@3.0.2
  ├── lodash.isarguments@3.0.4
  ├── lodash.isarray@3.0.4
  ├── lodash.istypedarray@3.0.2
  ├── lodash.keys@3.1.2
  ├── lodash.pad@3.1.1
  ├── lodash.padleft@3.1.1
  ├── lodash.padright@3.1.1
  ├── lodash.pairs@3.0.1
  ├── lodash.repeat@3.0.1
  ├── lodash.restparam@3.6.1
  ├── lodash.union@3.1.0
  ├── lodash.uniq@3.2.2
  ├── lodash.without@3.2.1
  ├── lru-cache@2.6.5
  ├── mime-db@1.18.0
  ├── mime-types@2.1.6
  ├── minimatch@2.0.10
  ├── minimist@0.0.8
  ├── mkdirp@0.5.1
  ├── ms@0.7.1
  ├── mute-stream@0.0.5
  ├─┬ node-gyp@3.0.3
  │ ├─┬ glob@4.5.3
  │ │ └── minimatch@2.0.10
  │ ├── minimatch@1.0.0
  │ └── tar@1.0.3
  ├── node-uuid@1.4.3
  ├── nopt@3.0.4
  ├── normalize-git-url@3.0.1
  ├── normalize-package-data@2.3.4
  ├── npm-cache-filename@1.0.2
  ├── npm-install-checks@2.0.0
  ├── npm-package-arg@4.0.2
  ├── npm-registry-client@7.0.7
  ├── npm-user-validate@0.1.2
  ├── npmlog@1.2.1
  ├── oauth-sign@0.8.0
  ├── once@1.3.2
  ├── opener@1.4.1
  ├── os-homedir@1.0.1
  ├── os-tmpdir@1.0.1
  ├── osenv@0.1.3
  ├── path-array@1.0.0
  ├── path-is-absolute@1.0.0
  ├── path-is-inside@1.0.1
  ├── process-nextick-args@1.0.3
  ├── promzard@0.3.0
  ├── proto-list@1.2.4
  ├── qs@5.1.0
  ├── read@1.0.7
  ├── read-cmd-shim@1.0.1
  ├── read-installed@4.0.3
  ├── read-package-json@2.0.1
  ├── read-package-tree@5.1.0
  ├── readable-stream@1.1.13
  ├── readdir-scoped-modules@1.0.2
  ├── realize-package-specifier@3.0.1
  ├── request@2.62.0
  ├── retry@0.8.0
  ├── rimraf@2.4.3
  ├── semver@5.0.3
  ├─┬ sha@2.0.1
  │ └── readable-stream@2.0.2
  ├── sigmund@1.0.1
  ├── slide@1.1.6
  ├── sntp@1.0.9
  ├── sorted-object@1.0.0
  ├── spdx-correct@1.0.1
  ├── spdx-exceptions@1.0.2
  ├── spdx-expression-parse@1.0.0
  ├── spdx-license-ids@1.0.2
  ├── string_decoder@0.10.31
  ├── stringstream@0.0.4
  ├── strip-ansi@3.0.0
  ├── supports-color@2.0.0
  ├── tar@2.2.1
  ├── text-table@0.2.0
  ├── tough-cookie@2.0.0
  ├── tunnel-agent@0.4.1
  ├── typedarray@0.0.6
  ├── uid-number@0.0.6
  ├── umask@1.1.0
  ├── unique-filename@1.0.0
  ├── unique-slug@1.0.0
  ├── unpipe@1.0.0
  ├── util-deprecate@1.0.1
  ├── util-extend@1.0.1
  ├── validate-npm-package-license@3.0.1
  ├── validate-npm-package-name@2.2.2
  ├── wcwidth@1.0.0
  ├── which@1.1.2
  ├── wrappy@1.0.1
  ├── write-file-atomic@1.1.3
  └── xtend@4.0.0
```

**Comment by clochix** [comment] 2015-09-27 20:09
Thanks a lot for the feedback.
So the problem is on Debian's side. I think we can close this ticket.

@nledez would you mind having a look a this ? Seems like the node-gyp installed in Debian is too old to compile some dependencies of the proxy :-S.

**Closed by clochix** 2015-09-27 20:09 UTC

**Comment by jeekajoo** [comment] 2015-09-28 15:08
I guess every user that installed cozy with official packages on debian jessie and updated cozy (like me) are now stuck because of this proxy issue ;) you can't even have cozy-home working anymore. So this is pretty serious.

**Comment by clochix** [comment] 2015-09-29 07:30
Yes, we downgraded the required version of bcrypt, so it can install with the npm version in Jessie. See https://github.com/cozy/cozy-proxy/pull/181

**Comment by jeekajoo** [comment] 2015-09-30 14:00
thanks @clochix @nono, I reverted npm and it is now ok.

**Comment by soichih** [comment] 2015-10-30 17:51
I was having the same issue.. on RHEL7. Did "npm -g install npm" and it fixed it.

**Comment by clochix** [comment] 2015-10-30 19:45
Hi @soichih,
Are you running Cozy on RHEL 7. We would be interested in hearing feedbacks on how you installed it and how it works in this distribution!
